[main]
font=monospace:size=9
dpi-aware=yes
term=xterm-256color

[colors]
# Xoria265
foreground=ffffd7
background=000000

regular0=000000  # Black
regular1=af5f5f  # Red
regular2=5f875f  # Green
regular3=87875f  # Yellow
regular4=5f87af  # Blue
regular5=5f5f87  # Magenta
regular6=5f8787  # Cyan
regular7=6c6c6c  # White

bright0=444444  # Bright Black
bright1=ff8700  # Bright Red
bright2=87af87  # Bright Green
bright3=ffffaf  # Bright Yellow
bright4=8fafd7  # Bright Blue
bright5=8787af  # Bright Magenta
bright6=5fafaf  # Bright Cyan
bright7=ffffd7  # Bright White

[mouse]
hide-when-typing=yes

[scrollback]
lines=10000

